const alphabet = "abcdefghijklmnopqrstuvwxyz";

export const levelLetterSets = {
  azerty: ["qsdfjklm", "gh", "azer", "tycv", "uiop", "wxbn", alphabet,],
  dvorak: ["aoeuhtns", "id", "pyfg", "kxbm", "crlw", "qjvz", alphabet,],
  colemak: ["arstneio", "dh", "pgjl", "cvbk", "wfuy", "qzxm", alphabet,],
  colemakdh: ["arstneio", "dh", "wfyu", "plgm", "bcvk", "qxjz", alphabet,],
  lefthandeddvorak: ["dtheac", "yurso", "gvwni", "mljc", "qbkx", "pfz", alphabet,],
  qwerty: ["asdfer", "jkliuo", "ghty", "qwzx", "nmp", "cvb", alphabet,],
  tarmak: ["arstneio", "dh", "gjvb", "qwfp", "luyz", "cxkm", alphabet,],
  workman: ["ashtneoi", "gy", "bjfu", "mcvk", "plzx", "qdrw", alphabet,],
  custom: ["", "", "", "", "", "", alphabet,],
};

export const allLayoutMaps = {
  azerty: {
    "-": ")",
    "=": "=",
    "q": "a",
    "w": "z",
    "e": "e",
    "r": "r",
    "t": "t",
    "y": "y",
    "u": "u",
    "i": "i",
    "o": "o",
    "p": "p",
    "[": "^",
    "]": "$",
    "\\": "\\",
    "a": "q",
    "s": "s",
    "d": "d",
    "f": "f",
    "g": "g",
    "h": "h",
    "j": "j",
    "k": "k",
    "l": "l",
    ";": "m",
    "'": "ù",
    "z": "<",
    "x": "w",
    "c": "x",
    "v": "c",
    "b": "v",
    "n": "b",
    "m": "n",
    ",": ".",
    ".": ";",
    "/": "!",
  },
  dvorak: {
    "-": "[",
    "=": "]",
    "q": "'",
    "w": ",",
    "e": ".",
    "r": "p",
    "t": "y",
    "y": "f",
    "u": "g",
    "i": "c",
    "o": "r",
    "p": "l",
    "[": "/",
    "]": "=",
    "\\": "\\",
    "a": "a",
    "s": "o",
    "d": "e",
    "f": "u",
    "g": "i",
    "h": "d",
    "j": "h",
    "k": "t",
    "l": "n",
    ";": "s",
    "'": "-",
    "z": ";",
    "x": "q",
    "c": "j",
    "v": "k",
    "b": "x",
    "n": "b",
    "m": "m",
    ",": "w",
    ".": "v",
    "/": "z",
    "Backquote": "`",
    "1": "1",
    "2": "2",
    "3": "3",
    shiftLayer: {
      "Q": '"',
      "W": "<",
      "E": ">",
      "R": "P",
      "T": "Y",
      "Y": "F",
      "U": "G",
      "I": "C",
      "O": "R",
      "P": "L",
      "{": "?",
      "A": "A",
      "S": "O",
      "D": "E",
      "F": "U",
      "G": "I",
      "H": "D",
      "J": "H",
      "K": "T",
      "L": "N",
      ";": "S",
      "Z": ":",
      "X": "Q",
      "C": "J",
      "V": "K",
      "B": "X",
      "N": "B",
      "M": "M",
      "<": "W",
      ">": "V",
      "?": "Z",
      "!": "!",
    },
  },
  colemak: {
    "-": "-",
    "=": "=",
    "q": "q",
    "w": "w",
    "e": "f",
    "r": "p",
    "t": "g",
    "y": "j",
    "u": "l",
    "i": "u",
    "o": "y",
    "p": ";",
    "[": "[",
    "]": "]",
    "\\": "\\",
    "a": "a",
    "s": "r",
    "d": "s",
    "f": "t",
    "g": "d",
    "h": "h",
    "j": "n",
    "k": "e",
    "l": "i",
    ";": "o",
    "'": "'",
    "z": "z",
    "x": "x",
    "c": "c",
    "v": "v",
    "b": "b",
    "n": "k",
    "m": "m",
    ",": ",",
    ".": ".",
    "/": "/",
  },
  colemakdh: {
    "-": "-",
    "=": "=",
    "q": "q",
    "w": "w",
    "e": "f",
    "r": "p",
    "t": "b",
    "y": "j",
    "u": "l",
    "i": "u",
    "o": "y",
    "p": ";",
    "[": "[",
    "]": "]",
    "\\": "\\",
    "a": "a",
    "s": "r",
    "d": "s",
    "f": "t",
    "g": "g",
    "h": "m",
    "j": "n",
    "k": "e",
    "l": "i",
    ";": "o",
    "'": "'",
    "z": "z",
    "x": "x",
    "c": "c",
    "v": "d",
    "b": "v",
    "n": "k",
    "m": "h",
    ",": ",",
    ".": ".",
    "/": "/",
  },
  lefthandeddvorak: {
    "1": "[",
    "2": "]",
    "3": "/",
    "4": "p",
    "5": "f",
    "6": "m",
    "7": "l",
    "8": "j",
    "9": "4",
    "0": "3",
    "-": "2",
    "=": "1",
    "q": ";",
    "w": "q",
    "e": "b",
    "r": "y",
    "t": "u",
    "y": "r",
    "u": "s",
    "i": "o",
    "o": ".",
    "p": "6",
    "[": "5",
    "]": "=",
    "\\": "\\",
    "a": "-",
    "s": "k",
    "d": "c",
    "f": "d",
    "g": "t",
    "h": "h",
    "j": "e",
    "k": "a",
    "l": "z",
    ";": "8",
    "'": "7",
    "z": "'",
    "x": "x",
    "c": "g",
    "v": "v",
    "b": "w",
    "n": "n",
    "m": "i",
    ",": ",",
    ".": "0",
    "/": "9",
  },
  tarmak: {
    "-": "1",
    "=": "=",
    "q": "q",
    "w": "w",
    "e": "f",
    "r": "p",
    "t": "g",
    "y": "j",
    "u": "l",
    "i": "u",
    "o": "y",
    "p": ";",
    "[": "[",
    "]": "]",
    "\\": "\\",
    "a": "a",
    "s": "r",
    "d": "s",
    "f": "t",
    "g": "d",
    "h": "h",
    "j": "n",
    "k": "e",
    "l": "i",
    ";": "o",
    "'": "'",
    "z": "z",
    "x": "x",
    "c": "c",
    "v": "v",
    "b": "b",
    "n": "k",
    "m": "m",
    ",": ",",
    ".": ".",
    "/": "/",
  },
  qwerty: {
    "-": "-",
    "=": "=",
    "q": "q",
    "w": "w",
    "e": "e",
    "r": "r",
    "t": "t",
    "y": "y",
    "u": "u",
    "i": "i",
    "o": "o",
    "p": "p",
    "[": "[",
    "]": "]",
    "\\": "\\",
    "a": "a",
    "s": "s",
    "d": "d",
    "f": "f",
    "g": "g",
    "h": "h",
    "j": "j",
    "k": "k",
    "l": "l",
    ";": ";",
    "'": "'",
    "z": "z",
    "x": "x",
    "c": "c",
    "v": "v",
    "b": "b",
    "n": "n",
    "m": "m",
    ",": ",",
    ".": ".",
    "/": "/",
  },
  workman: {
    "-": "-",
    "=": "=",
    "q": "q",
    "w": "d",
    "e": "r",
    "r": "w",
    "t": "b",
    "y": "j",
    "u": "f",
    "i": "u",
    "o": "p",
    "p": ";",
    "[": "[",
    "]": "]",
    "\\": "\\",
    "a": "a",
    "s": "s",
    "d": "h",
    "f": "t",
    "g": "g",
    "h": "y",
    "j": "n",
    "k": "e",
    "l": "o",
    ";": "i",
    "'": "'",
    "z": "z",
    "x": "x",
    "c": "m",
    "v": "c",
    "b": "v",
    "n": "k",
    "m": "l",
    ",": ",",
    ".": ".",
    "/": "/",
  },
}

export const emptyCustomKeyMap = {
  "-": " ",
  "=": " ",
  "q": " ",
  "w": " ",
  "e": " ",
  "r": " ",
  "t": " ",
  "y": " ",
  "u": " ",
  "i": " ",
  "o": " ",
  "p": " ",
  "[": " ",
  "]": " ",
  "\\": " ",
  "a": " ",
  "s": " ",
  "d": " ",
  "f": " ",
  "g": " ",
  "h": " ",
  "j": " ",
  "k": " ",
  "l": " ",
  ";": " ",
  "'": " ",
  "z": " ",
  "x": " ",
  "c": " ",
  "v": " ",
  "b": " ",
  "n": " ",
  "m": " ",
  ",": " ",
  ".": " ",
  "/": " ",
}

export const rowData = [
  [
    { class: "", id: "Backquote" },
    { class: "", id: "1" },
    { class: "", id: "2" },
    { class: "", id: "3" },
    { class: "", id: "4" },
    { class: "", id: "5" },
    { class: "", id: "6" },
    { class: "", id: "7" },
    { class: "", id: "8" },
    { class: "", id: "9" },
    { class: "", id: "0" },
    { class: "", id: "-" },
    { class: "", id: "=" },
    { class: "twou", id: "BackSpace" },
  ],
  [
    { class: "onepointfiveu" },
    { class: "", id: "q" },
    { class: "", id: "w" },
    { class: "", id: "e" },
    { class: "lvl3", id: "r" },
    { class: "lvl3", id: "t" },
    { class: "lvl3", id: "y" },
    { class: "lvl3", id: "u" },
    { class: "lvl5", id: "i" },
    { class: "lvl5", id: "o" },
    { class: "lvl5", id: "p" },
    { class: "", id: "[" },
    { class: "", id: "]" },
    { class: "onepointfiveu", id: "\\" },
  ],
  [
    { class: "onepointsevenfiveu" },
    { class: "lvl1", id: "a" },
    { class: "lvl1", id: "s" },
    { class: "lvl1", id: "d" },
    { class: "lvl1 restingPosition", id: "f" },
    { class: "lvl2", id: "g" },
    { class: "lvl2", id: "h" },
    { class: "lvl1 restingPosition", id: "j" },
    { class: "lvl1", id: "k" },
    { class: "lvl1", id: "l" },
    { class: "lvl1", id: ";" },
    { class: "", id: "'" },
    { class: "twopointtwofiveu" },
  ],
  [
    { class: "twopointtwofiveu" },
    { class: "", id: "z" },
    { class: "lvl6", id: "x" },
    { class: "lvl6", id: "c" },
    { class: "lvl4", id: "v" },
    { class: "lvl4", id: "b" },
    { class: "lvl4", id: "n" },
    { class: "lvl4", id: "m" },
    { class: "lvl5", id: "," },
    { class: "lvl6", id: "." },
    { class: "lvl6", id: "/" },
    { class: "twopointsevenfiveu" },
  ],
  [
    { class: "onepointtwofiveu" },
    { class: "onepointtwofiveu" },
    { class: "onepointtwofiveu" },
    { class: "sixpointtwofiveu" },
    { class: "onepointtwofiveu" },
    { class: "onepointtwofiveu" },
    { class: "onepointtwofiveu" },
    { class: "onepointtwofiveu" },
  ],
];
